# Generated by Django 5.1 on 2024-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_role_permissions_role_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='users.role'),
        ),
    ]
